# Generated by Django 5.2.1 on 2025-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='itinerary',
            field=models.TextField(),
        ),
    ]
