# Generated by Django 5.2.1 on 2025-06-20 09:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_package_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='package',
            name='duration',
            field=models.CharField(default='1 Day', max_length=50),
        ),
        migrations.AddField(
            model_name='package',
            name='pax',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='package',
            name='trip_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
